Subway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('schedule/',include('schedule.urls')),
    path('device/',include('device.urls')),
    path('material/', include('material.urls')),
    path('technology/', include('technology.urls')),
    path('safety/', include('safety.urls')),
    path('system/', include('system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from .views import *

app_name = "member"
urlpatterns = [

    path('', index),
    path('auth/login', LoginView.as_view(), name='login'),
    path('auth/logout', logout_view, name='logout'),
    path('global/qrcode/<path:data>', qrcode_view, name='qrcode'),
    path('global/success', success_view, name='success'),
    path('global/depass', depass_view, name='depass'),
    path('member/member_add', MemberAddView.as_view(), name='member_add'),
    path('member/member_list', MemberListView.as_view(), name='member_list'),
    path('member/member_update/<int:pk>', MemberUpdateView.as_view(), name='member_update'),
    path('member/member_delete/<int:pk>', MemberDeleteView.as_view(), name='member_delete'),
    path('member/member_list_detail', MemberListDetailView.as_view(), name='member_list_detail'),
    path('member/member_list_detail/<int:dept_id>', MemberListDetailView.as_view(), name='member_list_detail_with_id'),
    path('member/member_list/<int:dept_id>', MemberListView.as_view(), name='member_list_with_id'),
    path('member/member_import', import_member_data, name='member_import'),
    path('member/member_export', export_member_data, name='member_export'),
    path('member/member_export/<int:dept_id>', export_member_data, name='member_export_with_id'),
    path('member/member_detail/<str:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('member/dept', DeptListView.as_view(), name='dept_list'),
    path('member/dept_create', DeptCreateView.as_view(), name='dept_create'),
    path('member/dept_update/<int:pk>', DeptUpdateView.as_view(), name='dept_update'),
    path('member/dept_delete/<int:pk>', DeptDeleteView.as_view(), name='dept_delete'),
    path('member/dept_assign_account/<int:pk>', AssignAccountView.as_view(), name='dept_assign_account'),
    path('member/dept_assign_account/update/<int:pk>', AssignAccountUpdateView.as_view(), name='update_assign_account'),
    path('member/dept_assign_account/delete/<int:pk>', AssignAccountDeleteView.as_view(), name='delete_assign_account'),
    path('member/dept_assign_account_list', AssignAccountListView.as_view(), name='dept_assign_account_list'),
    path('member/dept_assign_account_list/<int:dept_id>', AssignAccountListView.as_view(), name='accout_list_with_id'),

    path('member/export_qr/<int:dept_id>', export_qr_with_dept, name='export_qr_with_dept')
]

member/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from Subway import settings
from .models import *
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class LoginForm(forms.Form):
    username = forms.CharField(
        label=u"用户名",
        error_messages={'required': u'请输入用户名'},
        widget=forms.TextInput(
            attrs={
                'class': 'validate',
                # 'placeholder': "用户名",
                'type': 'text',
            }
        ),
    )

    password = forms.CharField(
        required=True,
        label=u"密码",
        error_messages={'required': u'请输入密码'},
        widget=forms.PasswordInput(
            attrs={
                'class': 'validate',
                # 'placeholder': "密码",
                'type': 'password',
            }
        ),
    )

    def clean(self):
        if not self.is_valid():
            raise forms.ValidationError(u"用户名和密码为必填项")
        else:
            cleaned_data = super(LoginForm, self).clean()


class DeptCreateForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Departments
        fields = ['dept_name', 'dept_boss', 'dept_position', 'boos_phone']
        widgets = {
            'dept_name': forms.TextInput(attrs={'class': 'input', 'placeholder': '部门名称'}),
            'dept_boss': forms.TextInput(attrs={'class': 'input', 'placeholder': '部门负责人'}),
            'dept_position': forms.TextInput(attrs={'class': 'input', 'placeholder': '职位'}),
            'boos_phone': forms.TextInput(attrs={'type': 'tel', 'placeholder': '部门电话'})
        }


class AssignAccountForm(PopRequestMixin, CreateUpdateAjaxMixin, UserCreationForm):
    username = forms.CharField(
        label='用户名',
        help_text='必填。150个字符或者更少。包含字母，数字和仅有的@/./+/-/_符号。',
        widget=forms.TextInput(
            attrs={'class': 'input', 'placeholder': '用户名'})
    )

    last_name = forms.CharField(
        label='姓名',
        widget=forms.TextInput(
            attrs={'class': 'input'})
    )

    position = forms.CharField(
        label='职位',
        widget=forms.TextInput(
            attrs={'class': 'input'})
    )

    password1 = forms.CharField(label='密码',
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'input',
                                        'type': 'password'}))

    password2 = forms.CharField(label='重复密码',
                                widget=forms.TextInput(
                                    attrs={
                                        'class': 'input',
                                        'type': 'password'}))

    roles = forms.ModelMultipleChoiceField(label='分配权限', queryset=Role.objects.all(), help_text='分配权限，按住Ctrl多选', required=False)

    def _post_clean(self):
        super()._post_clean()
        # Validate the password after self.instance is updated with form data
        # by super().
        password = self.cleaned_data.get('password2')
        if settings.DEBUG:
            return
        if password:
            return
            # try:
            #     password_validation.validate_password(password, self.instance)
            # except forms.ValidationError as error:
            #     self.add_error('password2', error)

    class Meta(UserCreationForm.Meta):
        model = Account
        fields = ('username', 'last_name', 'position', 'password1', 'password2',)


class AccountUpdateForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    last_name = forms.CharField(
        label='姓名',
        widget=forms.TextInput(
            attrs={'class': 'input'})
    )

    class Meta:
        model = Account
        fields = ['username', 'enp', 'last_name', 'position', 'roles']


class MemberForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'


class MemberUpdateForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = '__all__'

member/views.py
from datetime import datetime

import django_excel as excel
from bootstrap_modal_forms.mixins import DeleteAjaxMixin, PassRequestMixin
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError, transaction
from django.http import Http404, JsonResponse
from django.shortcuts import HttpResponse, get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, FormView,
                                  ListView, UpdateView, View)

from core.init_permission import *
from core.utils import *

from bootstrap_modal_forms.mixins import PassRequestMixin, DeleteAjaxMixin
from .forms import *
from .models import *


class LoginView(FormView):
    template_name = 'user/login.html'
    form_class = LoginForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None and user.is_active:
                init_permission(user, request)
                return self.form_valid(form, user)
            else:
                return self.form_invalid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form, user=None):
        login(self.request, user)
        return super().form_valid(form)


def logout_view(request):
    logout(request)
    return redirect('/')


class AssignAccountView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Account
    template_name = "dept/dept_assign_account_form.html"
    form_class = AssignAccountForm
    success_message = '添加成功'
    success_url = reverse_lazy('member:dept_list')

    def get(self, request, *args, **kwargs):
        self.dept = get_object_or_404(Departments, pk=kwargs.get('pk'))
        return super(AssignAccountView, self).get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.dept = get_object_or_404(Departments, pk=kwargs.get('pk'))
        return super(AssignAccountView, self).post(self, request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()
        self.object.enp = en_password(form.cleaned_data.get('password1'))
        self.object.user_dept = self.dept
        self.object.roles.add(*list(form.cleaned_data.get('roles')))
        return super(AssignAccountView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(AssignAccountView, self).get_context_data(**kwargs)
        context['dept'] = self.dept

        return context


class AssignAccountUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Account
    template_name = 'dept/assign_account_update_form.html'
    form_class = AccountUpdateForm
    success_message = '更新成功'
    success_url = reverse_lazy("member:dept_assign_account_list")

    def form_valid(self, form):
        self.object = form.save()
        self.object.enp = en_password(form.cleaned_data.get('enp'))
        self.object.set_password(form.cleaned_data.get('enp'))
        self.object.roles.clear()
        self.object.roles.add(*list(form.cleaned_data.get('roles')))
        return super(AssignAccountUpdateView, self).form_valid(form)


class AssignAccountDeleteView(DeleteAjaxMixin, DeleteView):
    model = Account
    template_name = "dept/assign_account_delete_form.html"
    success_message = '删除成功'
    success_url = reverse_lazy("member:dept_assign_account_list")


class AssignAccountListView(ListView):
    template_name = 'dept/assign_account_list.html'
    model = Account

    @method_decorator(login_required(login_url='/auth/login'))
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_superuser:
            return render(self.request, self.template_name, {'msg': 'no'})
        return super(AssignAccountListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        self.dept_id = kwargs.get('dept_id', 0)
        return super(AssignAccountListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(AssignAccountListView,
                         self).get_queryset().filter(enp__isnull=False)
        if self.dept_id:
            queryset = queryset.filter(user_dept_id=self.dept_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(AssignAccountListView, self).get_context_data(**kwargs)
        context['dept_list'] = Departments.objects.all()

        if self.dept_id:
            context['select_dept'] = get_object_or_404(
                Departments, pk=self.dept_id).dept_name
        else:
            context['select_dept'] = '全部'

        return context


class DeptListView(ListView):
    template_name = 'dept/dept_list.html'
    model = Departments
    paginate_by = 100

    @method_decorator(login_required(login_url='/auth/login'))
    def dispatch(self, *args, **kwargs):
        if not self.request.user.is_superuser:
            return render(self.request, self.template_name, {'msg': 'no'})
        return super(DeptListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        queryset = super(DeptListView, self).get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super(DeptListView, self).get_context_data(**kwargs)
        context['roles'] = Role.objects.all()

        return context


class DeptCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Departments
    template_name = "dept/dept_create_form.html"
    form_class = DeptCreateForm
    success_message = '添加成功'
    success_url = reverse_lazy('member:dept_list')


class DeptUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Departments
    template_name = "dept/dept_update_form.html"
    form_class = DeptCreateForm
    success_message = '更新成功'
    success_url = reverse_lazy('member:dept_list')


class DeptDeleteView(DeleteAjaxMixin, DeleteView):
    model = Departments
    template_name = "dept/dept_delete_form.html"
    success_message = '删除成功'
    success_url = reverse_lazy("member:dept_list")


class MemberAddView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Member
    form_class = MemberForm
    template_name = "member/member_add_update_form.html"
    success_message = '添加成功'
    success_url = reverse_lazy('member:member_list')


class MemberDeleteView(DeleteAjaxMixin, DeleteView):
    model = Member
    template_name = "member/member_delete_form.html"
    success_message = '删除成功'
    success_url = reverse_lazy("member:member_list")


class MemberListView(ListView):
    template_name = 'member/member_list.html'
    model = Member

    @method_decorator(login_required(login_url='/auth/login'))
    def dispatch(self, *args, **kwargs):
        return super(MemberListView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        dept_id = kwargs.get('dept_id')
        self.dept = None

        if dept_id is None:
            if not request.user.is_superuser:
                self.dept = self.request.user.user_dept
        else:
            if not request.user.is_superuser and dept_id != self.request.user.user_dept_id:
                # TODO: xx
                self.dept = self.request.user.user_dept
            else:
                self.dept = get_object_or_404(Departments, pk=dept_id)

        return super(MemberListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(MemberListView, self).get_queryset()
        if not self.dept:
            queryset = queryset
        else:
            queryset = queryset.filter(dept=self.dept)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(MemberListView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context['dept_list'] = Departments.objects.all()
            if self.dept is not None:
                context['select_dept'] = self.dept.dept_name
                context['download_dept'] = self.dept.id
            else:
                context['select_dept'] = '全部'
                context['download_dept'] = 0
        else:
            context['dept_list'] = Departments.objects.filter(
                pk=self.request.user.user_dept.id)
            context['select_dept'] = self.dept.dept_name
            context['download_dept'] = self.dept.id
        return context


class MemberListDetailView(MemberListView):
    template_name = 'member/member_list_detail.html'


class MemberUpdateView(UpdateView):
    model = Member
    template_name = "member/member_add_update_form2.html"
    form_class = MemberUpdateForm
    success_message = '%s 更新成功'
    success_url = reverse_lazy('member:member_list')


class MemberDetailView(DetailView):
    model = Member
    template_name = "member/mobile.html"

    def get_context_data(self, **kwargs):
        context = super(MemberDetailView, self).get_context_data(**kwargs)
        return context


def qrcode_view(request, data):
    img = gen_qrcode(data)
    response = HttpResponse(img, content_type="image/png")

    return response


def import_member_data(request):
    # 导入数据
    mapdict = {
        "员工工号": 'member_id',
        "部门id": 'dept_id',
        "部门名字": 'dept_name',
        '姓名': 'name',
        '性别': 'sex',
        '生日': 'birthday',
        '职位': 'position',
        '电话': 'phone',
        '民族': 'nation',
        '血型': 'blood_type'
    }
    if request.method == "POST":
        try:

templates/member/assign_account_delete_form.html
<form method="post" action="">
    {% csrf_token %}
    <div class="ui icon header">
        <i class="remove user icon">
        </i> 确认删除账号"{{ account.username }}"吗?
    </div>

    <div class="actions">
        <div class="ui red  cancel inverted button"><i class="remove icon"></i> 否</div>
        <button type="submit" class="ui green ok inverted button"><i class="checkmark icon"></i> 是</button>
    </div>
</form>
{% block style %}
    <style>
        .modal-content form {
            text-align: center;
        }

        .actions {
            margin: 20px;
        }

    </style>
{% endblock %}

templates/member/assign_account_update_form.html
<form action="" method="POST" class="depart_update_form">
    <div class="ui dividing header">更新账号</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div class="ui form">
            {% for field in form %}
            <div class="field">

                {{ field.label }}
                {{ field }}

                {% if field.help_text %}
                    <br><br>
                    {{ field.help_text }}
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="help-block ui negative message">{{ error }}</p>
                    {% endfor %}
                </div>
                <br>
            {% endfor %}
            </div>
        </div>
        <div class="actions">
            <div class="ui black  deny button">取消</div>
            <button type="submit" class="ui submit-btn btn positive  labeled icon button">
                提交
                <i class="checkmark icon"></i>
            </button>
        </div>
</form>

templates/member/dept_update_form.html
<div class="header">更新部门</div>
<form action="" method="POST" class="depart">

    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="ui form">
            <div class="four fields">
                <div class="field">{{ form.dept_name }}</div>
                <div class="field">{{ form.dept_boss }}</div>
                <div class="field">{{ form.dept_position }}</div>
                <div class="field">{{ form.boos_phone }}
                </div>
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <<button type="submit" class="ui positive right labeled icon button">提交<i class="checkmark icon"></i>
        </button>

    </div>
</form>

templates/member/member_add_update_form.html
<form method="post" enctype="multipart/form-data">
    <div class="ui dividing header">添加成员</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div class="ui form">
            <div class="four fields">
                {% for field in form %}
                    <div class="field">{{ field }}</div>
                    <div class="{% if field.errors %} invalid{% endif %}">
                        {% for error in field.errors %}
                            <p class="ui negative message" style="padding: 0;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                class="checkmark icon"></i>
        </button>
    </div>
</form>

templates/member/member_delete_form.html
<form method="post" action="">
    {% csrf_token %}
    <div class="ui icon header">
        <i class="remove user icon">
        </i> 确认删除员工"{{ member.name }} 员工号为{{ member.member_id }}"吗?
    </div>
    <div class="actions">
        <div class="ui red  cancel inverted button"><i class="remove icon"></i> 否</div>
        <button type="submit" class="ui green ok inverted button"><i class="checkmark icon"></i> 是</button>
    </div>
</form>
{% block style %}
    <style>
        .modal-content form {
            text-align: center;
        }

        .actions {
            margin: 20px;
        }

    </style>
{% endblock %}

templates/member/member_list.html
{% extends "base.html" %}
{% block content %}
    {% include "_modal.html" %}
    {% load fun_filter %}

    <section>
        <div class="ui segment">
            <h1 class="ui header aligned center">员工信息</h1>
            <div class="ui floating labeled icon dropdown button"><i class="filter icon"></i>
                <label>{{ select_dept }}</label>
                <div class="menu">
                    <div class="header"><i class="tags icon"></i>选取部门</div>
                    <div class="divider"></div>
                    <a class="item" href="{% url 'member:member_list' %}">全部 </a>
                    {% for dept in dept_list %}
                        <a class="item" href="{% url 'member:member_list_with_id' dept.id %}">{{ dept.dept_name }} </a>
                    {% endfor %}
                </div>
            </div>
            <a href="{% url 'member:member_list_detail' %}">
                <button class="ui right labeled icon button primary"><i class="right info icon"></i> 查看详细</button>
            </a>
            <div class="ui animated fade right floated button">
                <div class="hidden content"><i class="upload icon"></i></div>
                <a class="visible content" href="{% url 'member:export_qr_with_dept' download_dept %}">导出{{select_dept}}部门二维码</a>
            </div>
            <div class="ui buttons right floated">
                <form action="{% url 'member:member_import' %}" id="import_form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="ui labeled icon button right floated my_import" id="import"><i
                            class="upload icon"></i>
                        导入
                    </div>
                </form>
                <div class="or"></div>
                {% ifequal download_dept 0 %}
                    <a class="ui right labeled icon button my_export" href="{% url 'member:member_export' %}"><i
                            class="download icon"></i>
                        导出</a>
                {% else %}
                    <a class="ui right labeled icon button my_export"
                       href="{% url 'member:member_export_with_id' download_dept %}"><i
                            class="upload icon"></i> 导出</a>
                {% endifequal %}
            </div>
            <table class="ui table celled line single fixed" id="table">
                <thead>
                <tr class="center aligned">
                    <th>员工工号</th>
                    <th>姓名</th>
                    <th>职位</th>
                    <th>部门</th>
                    <th>联系方式</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for member in object_list %}
                    <tr class="center aligned">
                        <td>{{ member.member_id }}</td>
                        <td>{{ member.name }}</td>
                        <td>{{ member.position }}</td>
                        <td>{{ member.dept }}</td>
                        <td>{{ member.phone }}</td>
                        <td><a class="ui vertical animated button positive basic right floated my_qrcode"
                               href="{{ member.qrcode }}"
                               download>
                            <div class="hidden content">二维码</div>
                            <div class="visible content"><i class="qrcode icon"></i></div>
                        </a><a class="ui vertical animated button primary basic left floated my_edit_member">
                            <div class="hidden content update_member"
                                 data-id="{% url 'member:member_update' member.id %}">编辑
                            </div>
                            <div class="visible content"><i class="edit icon"></i></div>
                        </a><a class="ui vertical animated button negative basic center floated my_remove">
                            <div class="hidden content delete_member"
                                 data-id="{% url 'member:member_delete' member.id %}">删除
                            </div>
                            <div class="visible content"><i class="remove user icon"></i></div>
                        </a></td>
                    </tr>
                {% empty %}
                    <div class="ui icon orange message"><i class="hide icon"></i>
                        <div class="content">
                            <div class="header">目前没有一条数据</div>
                            <p>请试着添加一条数据后再试。</p>
                        </div>
                    </div>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="6">
                        {% if member_add or user.is_superuser %}
                            <button class="ui labeled icon button positive right floated add_member"
                                    data-id="{% url 'member:member_add' %}"><i
                                    class="users icon"></i>
                                添加员工
                            </button>
                        {% endif %}
                        {% include '_page.html' %}
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </section>
{% endblock content %}


{% block script %}
    <script>
        $('.add_member').click(function () {
            {#var w = window.open("{% url "member:member_add" %}", "", "width=800,height=500")#}
            $(this).modalForm({formURL: $(this).data('id')})
        })
        $('.update_member').click(function () {
            var w = window.open($(this).data('id'), "", "width=800,height=500")
        })
        $('.delete_member').each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })


        $('.ui.dropdown').dropdown()
    </script>
{% endblock %}

templates/member/member_list_detail.html
{% extends 'base.html' %}

{% block content %}
    <section>
        <div class="ui segment">
            <h1 class="ui header aligned center">员工详细信息</h1>
            <div class="ui floating labeled icon dropdown button"><i class="filter icon"></i>
                <label>{{ select_dept }}</label>
                <div class="menu">
                    <div class="header"><i class="tags icon"></i>选取部门</div>
                    <div class="divider"></div>
                    <a class="item" href="{% url 'member:member_list' %}">全部 </a>
                    {% for dept in dept_list %}
                        <a class="item"
                           href="{% url 'member:member_list_detail_with_id' dept.id %}">{{ dept.dept_name }} </a>
                    {% endfor %}
                </div>
            </div>
            <a href="{% url 'member:member_list' %}">
                <button class="ui right labeled icon button primary basic"><i class="right info icon"></i> 查看缩略</button>
            </a>
            <table class="ui table celled line single fixed" id="table">
                <thead>
                <tr class="center aligned">
                    <th>员工工号</th>
                    <th>头像</th>
                    <th>姓名</th>
                    <th>性别</th>
                    <th>民族</th>
                    <th>血型</th>
                    {# <th>身份证</th>#}
                    <th>出生年月</th>
                    <th>职位</th>
                    <th>部门</th>
                    <th>联系方式</th>
                </tr>
                </thead>
                <tbody>
                {% for object in object_list %}
                    <tr class="center aligned">

                        <td>{{ object.member_id }}</td>
                        <td><img class="ui small image rounded my_img" src="{{ object.member_avatar.url }}"></td>
                        <td>{{ object.name }}</td>
                        <td>{{ object.sex }}</td>
                        <td>{{ object.nation }}</td>
                        <td>{{ object.blood_type }}</td>
                        {# <td>6101221999999999</td>#}
                        <td>{{ object.birthday }}</td>
                        <td>{{ object.position }}</td>
                        <td>{{ object.dept }}</td>
                        <td>{{ object.phone }}</td>
                        {% empty %}
                        <div class="ui icon orange message"><i class="hide icon"></i>
                            <div class="content">
                                <div class="header">目前没有一条数据</div>
                                <p>请试着添加一条数据后再试。</p>
                            </div>
                        </div>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    {% include '_page.html' %}
                </tr>
                </tfoot>
            </table>
        </div>
    </section>
{% endblock content %}
{% block script %}
    <script>$('.ui.dropdown').dropdown()</script>
{% endblock %}