Subway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('schedule/',include('schedule.urls')),
    path('device/',include('device.urls')),
    path('material/', include('material.urls')),
    path('technology/', include('technology.urls')),
    path('safety/', include('safety.urls')),
    path('system/', include('system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

member/urls.py
from django.urls import path
from .views import *

app_name = "member"
urlpatterns = [

    path('', index),
    path('auth/login', LoginView.as_view(), name='login'),
    path('auth/logout', logout_view, name='logout'),
    path('global/qrcode/<path:data>', qrcode_view, name='qrcode'),
    path('global/success', success_view, name='success'),
    path('global/depass', depass_view, name='depass'),
    path('member/member_add', MemberAddView.as_view(), name='member_add'),
    path('member/member_list', MemberListView.as_view(), name='member_list'),
    path('member/member_update/<int:pk>', MemberUpdateView.as_view(), name='member_update'),
    path('member/member_delete/<int:pk>', MemberDeleteView.as_view(), name='member_delete'),
    path('member/member_list_detail', MemberListDetailView.as_view(), name='member_list_detail'),
    path('member/member_list_detail/<int:dept_id>', MemberListDetailView.as_view(), name='member_list_detail_with_id'),
    path('member/member_list/<int:dept_id>', MemberListView.as_view(), name='member_list_with_id'),
    path('member/member_import', import_member_data, name='member_import'),
    path('member/member_export', export_member_data, name='member_export'),
    path('member/member_export/<int:dept_id>', export_member_data, name='member_export_with_id'),
    path('member/member_detail/<str:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('member/dept', DeptListView.as_view(), name='dept_list'),
    path('member/dept_create', DeptCreateView.as_view(), name='dept_create'),
    path('member/dept_update/<int:pk>', DeptUpdateView.as_view(), name='dept_update'),
    path('member/dept_delete/<int:pk>', DeptDeleteView.as_view(), name='dept_delete'),
    path('member/dept_assign_account/<int:pk>', AssignAccountView.as_view(), name='dept_assign_account'),
    path('member/dept_assign_account/update/<int:pk>', AssignAccountUpdateView.as_view(), name='update_assign_account'),
    path('member/dept_assign_account/delete/<int:pk>', AssignAccountDeleteView.as_view(), name='delete_assign_account'),
    path('member/dept_assign_account_list', AssignAccountListView.as_view(), name='dept_assign_account_list'),
    path('member/dept_assign_account_list/<int:dept_id>', AssignAccountListView.as_view(), name='accout_list_with_id'),

    path('member/export_qr/<int:dept_id>', export_qr_with_dept, name='export_qr_with_dept')
]

schedule/urls.py
from django.urls import path
from .views import *

app_name = "schedule"
urlpatterns = [
    path('list', ScheduleListView.as_view(), name='list'),
    path('list_detail', ScheduleListDetailView.as_view(), name='list_detail'),
    path('list_profess/<int:profess_id>', ScheduleListView.as_view(), name="list_profess"),
    path('list_detail/<int:profess_id>', ScheduleListDetailView.as_view(), name='list_detail_with_profess'),
    path('list_chart', ScheduleListChartView.as_view(), name='list_chart'),
    path('list_chart/<int:profess_id>', ScheduleListChartView.as_view(), name='list_chart_with_profess'),

    path('add', ScheduleAddView.as_view(), name='add'),
    path('update/<int:pk>', ScheduleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ScheduleDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', ScheduleDetailView.as_view(), name='detail'),
    path('item_chart/<int:pk>', ScheduleItemChartView.as_view(), name='item_chart'),

    path('init_profess', ProfessInitView.as_view(), name='init_profess'),
    path('add_profess', ProfessCreateView.as_view(), name='add_profess'),
    path('update_profess/<int:pk>', ProfessUpdateView.as_view(), name='update_profess'),
    path('delete_profess/<int:pk>', ProfessDeleteView.as_view(), name='delete_profess'),
]

schedule/models.py
from django.db import models


class Schedule(models.Model):
    """Model definition for Schedule."""

    # TODO: Define fields here

    class Meta:
        """Meta definition for Schedule."""

        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'

    def __str__(self):
        """Unicode representation of Schedule."""
        return self.name

    @property
    def undone_count(self):
        return self.design_total - self.done_count
    
    # 编号 暂定自增
    id = models.AutoField(primary_key=True, verbose_name='编号')
    job_name = models.CharField(max_length=50, verbose_name='作业名称')
    unit = models.CharField(max_length=10, verbose_name='单位')
    location = models.CharField(max_length=30, verbose_name='施工地点')
    done_count = models.IntegerField(default=0, verbose_name='开累完成量')
    design_total = models.IntegerField(default=0, verbose_name='设计总量')
    last_week_plan = models.IntegerField(default=0, verbose_name='上周计划完成量')
    last_week_actual = models.IntegerField(default=0, verbose_name='上周实际完成量')
    now_week_plan = models.IntegerField(default=0, verbose_name='本周计划完成量')
    now_week_actual = models.IntegerField(default=0, verbose_name='完成总周数')
    now_week = models.IntegerField(default=1, verbose_name='当前周目')
    profess = models.ForeignKey(to="Profess", related_name='profess',
                                on_delete=models.SET_NULL, verbose_name='专业', null=True)

class Profess(models.Model):
    """Model definition for Profess."""
    name = models.CharField(max_length=30)

    class Meta:
        """Meta definition for Profess."""

        verbose_name = 'Profess'
        verbose_name_plural = 'Professs'

    def __str__(self):
        """Unicode representation of Profess."""
        return self.name

schedule/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Schedule, Profess


class ScheduleForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Schedule
        fields = '__all__'


class ProfessForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):

    class Meta:

        model = Profess
        fields = '__all__'

schedule/views.py
from bootstrap_modal_forms.mixins import DeleteAjaxMixin, PassRequestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError, transaction
from django.http import JsonResponse
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                              get_object_or_404, render)
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)
from .forms import *

class ScheduleAddView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Schedule
    form_class = ScheduleForm
    template_name = 'schedule/schedule_create_form.html'
    success_url = reverse_lazy('schedule:list')
    success_message = '%(job_name)s 添加成功'


class ScheduleUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Schedule
    form_class = ScheduleForm
    template_name = 'schedule/schedule_update_form.html'
    success_url = reverse_lazy('schedule:list')
    success_message = '%(job_name)s 更新成功'


class ScheduleDetailView(DetailView):
    model = Schedule
    template_name = "TEMPLATE_NAME"


class ScheduleDeleteView(DeleteAjaxMixin, DeleteView):
    model = Schedule
    form_class = ScheduleForm
    template_name = 'schedule/schedule_delete_form.html'
    success_url = reverse_lazy('schedule:list')


class ScheduleListView(ListView):
    model = Schedule
    template_name = "schedule/schedule.html"
    paginate_by = 100

    def __init__(self):
        super().__init__()
        self.profess_all = Profess.objects.all()
        self.profess = self.profess_all[0] if len(self.profess_all) > 0 else 0

    def get(self, request, *args, **kwargs):
        if not self.profess:
            return HttpResponseRedirect(reverse_lazy('schedule:init_profess'))
        profess_id = kwargs.get('profess_id')
        if profess_id:
            self.profess = get_object_or_404(Profess, pk=profess_id)

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(ScheduleListView, self).get_queryset()
        queryset = queryset.filter(profess=self.profess)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['profess_s'] = self.profess_all
        context['select_profess'] = self.profess
        return context


class ScheduleListDetailView(ScheduleListView):
    model = Schedule
    template_name = "schedule/schedule_detail.html"


class ScheduleListChartView(ScheduleListView):
    model = Schedule
    template_name = "schedule/schedule_chart.html"


class ScheduleDetailView(DetailView):
    model = Schedule
    template_name = "NAME"


class ScheduleItemChartView(DetailView):
    model = Schedule
    template_name = "schedule/schedule_item.html"


class ProfessCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Profess
    form_class = ProfessForm
    template_name = "schedule/add_update_profess_form.html"
    success_message = '%(name)s 添加成功'
    success_url = reverse_lazy('schedule:list')


class ProfessInitView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Profess
    form_class = ProfessForm
    template_name = "schedule/init_profess_form.html"
    success_message = '%(name)s 添加成功'
    success_url = reverse_lazy('schedule:list')


class ProfessUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Profess
    form_class = ProfessForm
    template_name = "schedule/add_update_profess_form.html"
    success_message = '%(name)s 更新成功'
    success_url = reverse_lazy('schedule:list')


class ProfessDeleteView(DeleteView):
    model = Profess
    form_class = ProfessForm
    success_message = '%(name)s 删除成功'
    template_name = "schedule/delete_profess.html"
    success_url = reverse_lazy('schedule:list')

templates/schedule/add_update_profess_form.html
<form method="post" enctype="multipart/form-data">
    <div class="ui dividing header">修改/增加专业信息</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div class="ui form">
            <div class="four fields">
                {% for field in form %}
                    <div class="field">{{ field }}</div>
                    <div class="{% if field.errors %} invalid{% endif %}">
                        {% for error in field.errors %}
                            <p class="ui negative message" style="padding: 0;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                class="checkmark icon"></i>
        </button>
    </div>
</form>

templates/schedule/delete_profess.html
<form method="post" action="">
    {% csrf_token %}
    <div class="ui icon header">
        <i class="remove user icon">
        </i> 确认删除名字为"{{ profess.name }}"的专业吗?
    </div>
    <div class="actions">
        <div class="ui red  cancel inverted button"><i class="remove icon"></i> 否</div>
        <button type="submit" class="ui green ok inverted button"><i class="checkmark icon"></i> 是</button>
    </div>
</form>
{% block style %}
    <style>
        .modal-content form {
            text-align: center;
        }

        .actions {
            margin: 20px;
        }

    </style>
{% endblock %}

templates/schedule/init_profess_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="ui container" style="margin-top: 30vh">
        <div class="ui segment">
            <div class="ui dividing header">初始化专业信息</div>
            <form method="post" enctype="multipart/form-data">
                <!--i.close.icon-->
                {% csrf_token %}
                <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
                <div class="ui form">
                    <div class="fields">
                        {% for field in form %}
                            <div class="field">
                                {#                                <label for="">{{ field.label }}</label>#}
                                <label for=""> 添加专业名称</label>
                                {{ field }}</div>
                            <div class="{% if field.errors %} invalid{% endif %}">
                                {% for error in field.errors %}
                                    <p class="ui negative message" style="padding: 0;">{{ error }}</p>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="actions">
                    <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                            class="checkmark icon"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/schedule/schedule.html
{% extends 'base.html' %}
{% block content %}
    {% include "_modal.html" %}
    <section>
        <div class="ui segment"><h1 class="ui header aligned center">进度管理</h1>
            <div class="ui secondary pointing menu">

                {% for profess in profess_s %}
                    <a class="item
            {% ifequal select_profess profess %}
                active
            {% endifequal %}
                " href="{% url 'schedule:list_profess' profess.id %}">{{ profess.name }}</a>
                {% endfor %}
                <div class="right menu">
                    <a href="" class="item">导出全部专业二维码</a>
                    <a href="#" class="item add_profess" onclick="return false">添加专业</a>

                </div>
            </div>
            <a href="{% url 'schedule:list_detail_with_profess' select_profess.id %}">
                <button class="ui right labeled icon button primary"><i class="right info icon"></i>进度详情</button>
            </a>
            <div class="ui animated fade right floated button">
                <div class="hidden content"><i class="upload icon"></i></div>
                <div class="visible content">导出全部二维码</div>
            </div>
            <div class="ui buttons right floated">
                <button class="ui labeled icon button right floated my_import"><i class="download icon"></i> 导入</button>
                <div class="or"></div>
                <button class="ui right labeled icon button my_export"><i class="upload icon"></i> 导出</button>
            </div>
            <table class="ui table celled line single fixed" id="table">
                <thead>
                <tr class="center aligned">
                    <th>编号</th>
                    <th>施工地点</th>
                    <th>作业名称</th>
                    <th>专业</th>
                    <th>单位</th>
                    <th>开累完成率</th>
                    <th>设计总量</th>
                    <th>开累完成量</th>
                    <th>剩余总量</th>
                    <th class="four wide">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                    <tr class="center aligned">
                        <td>{{ item.id }}</td>
                        <td>{{ item.location }}</td>
                        <td>{{ item.job_name }}</td>
                        <td>{{ item.profess }}</td>
                        <td>{{ item.unit }}</td>
                        <td>{% widthratio item.done_count item.design_total 100 %}%</td>
                        <td>{{ item.design_total }}</td>
                        <td>{{ item.done_count }}</td>
                        <td>{{ item.undone_count }}</td>
                        <td><a class="ui vertical animated button positive basic center floated qrcode">
                            <div class="visible content">二维码</div>
                            <div class="hidden content"><i class="qrcode icon"></i></div>
                        </a><a class="ui vertical animated button primary basic center floated edit">
                            <div class="visible content">编辑</div>
                            <div class="hidden content update_schedule" data-id="{% url 'schedule:update' item.id %}"><i
                                    class="edit icon"></i></div>
                        </a><a class="ui vertical animated button primary basic center floated"
                               href="{% url 'schedule:item_chart' item.id %}">
                            <div class="visible content">任务报表</div>
                            <div class="hidden content"><i class="edit icon"></i></div>
                        </a><a class="ui vertical animated button negative basic center floated remove">
                            <div class="visible content">删除</div>
                            <div class="hidden content delete_schedule" data-id="{% url 'schedule:delete' item.id %}"><i
                                    class="remove user icon"></i></div>
                        </a></td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="10">
                        <button class="ui labeled icon button positive right floated add_schedule"><i
                                class="users icon"></i>
                            添加任务
                        </button>
                        <button class="ui labeled icon button blue left floated update_profess"><i
                                class="users icon"></i><span>
                                修改当前专业信息</span>
                        </button>
                        <button class="ui labeled icon button negative left floated delete_profess
                            {% ifequal object_list|length 0 %}
                            {% else %}
                            disabled
                            {% endifequal %}"
                        <i class=" users icon"></i><span> 删除当前专业</span>
                        </button>
                        <a class="ui labeled icon button black basic left floated append"
                           href="{{ select_profess.qrcode }}" download><i
                                class="users icon"></i><span>导出该专业二维码</span></a>
                        {% include '_page.html' %}
                    </th>
                </tr>
                </tfoot>
            </table><!-- item 操作-->
        </div>
    </section>
{% endblock %}
{% block script %}
    <script>
        $('.add_schedule').each(function () {
            $(this).modalForm({formURL: "{% url 'schedule:add' %}"})
        })
        $(".update_schedule").each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })
        $(".delete_schedule").each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })
        $('.add_profess').modalForm({formURL: '{% url 'schedule:add_profess' %}'})
        $('button.update_profess').modalForm({formURL: '{% url 'schedule:update_profess' select_profess.id %}'})
        $('button.delete_profess').modalForm({formURL: '{% url 'schedule:delete_profess' select_profess.id %}'})
        {% if profess_isValid %}
            alert("{{ profess_isValid}}")
        {% endif %}
    </script>
{% endblock %}

templates/schedule/schedule_chart.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <script src={% static 'javascript/g2/g2.min.js' %}></script>
    <script src={% static 'javascript/g2/data-set.min.js' %}></script>
{% endblock %}
{% block content %}
    <section>
        <div class="ui segment"><h1 class="ui header aligned center">进度总图表</h1>
            <div class="ui floating labeled icon dropdown button"><i class="filter icon"></i><span
                    class="text">{{ select_profess }}</span>
                <div class="menu">
                    <div class="header"><i class="tags icon"></i>选取专业</div>
                    <div class="divider"></div>
                    {% for profess in profess_s %}
                        <a class="item" href="{% url 'schedule:list_chart_with_profess' profess.id%}" > {{profess}}</a>
                    {% endfor %}
                </div>

            </div>
            <div style="overflow:hidden">
                <div id="mountNode"></div>
                <div class="bottom-tool-box"><img class="sort-button" src="../static/sort.png"></div>
            </div>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script>
        var sortType = 'positive'
        var data = [ {% for item in object_list %}{type: '{{item.job_name}}' ,value:{{item.done_count}}}, {% endfor %}]
        console.log(data)
        var data1 = [{
            type: '设备安装1',
            value: 34
        }, {
            type: '设备安装2',
            value: 85
        }, {
            type: '设备安装3',
            value: 103
        }, {
            type: '设备安装4',
            value: 142
        }, {
            type: '设备安装5',
            value: 251
        }, {
            type: '设备安装6',
            value: 367
        }, {
            type: '设备安装7',
            value: 491
        }, {
            type: '设备安装8',
            value: 672
        }, {
            type: '设备安装9',
            value: 8688
        }, {
            type: '设备安装',
            value: 1234
        }]
        var chart = new G2.Chart({
            container: 'mountNode',
            forceFit: true,
            height: window.innerHeight,
            padding: [20, 40, 50, 124]
        })
        chart.source(data, {
            value: {
                max: 100,
                min: 0,
                nice: false,
                alias: '开累量'
            }
        })
        chart.axis('type', {
            label: {
                textStyle: {
                    fill: '#8d8d8d',
                    fontSize: 18
                }
            },
            tickLine: {
                alignWithLabel: false,
                length: 0
            },
            line: {
                lineWidth: 0
            }
        })
        chart.axis('value', {
            label: null,
            title: {
                offset: 30,
                textStyle: {
                    fontSize: 18,
                    fontWeight: 300
                }
            }
        })
        chart.legend(false)
        chart.coord().transpose()
        chart.interval().position('type*value').size(26).opacity(1).label('value', {
            textStyle: {
                fill: '#8d8d8d'
            },
            offset: 10
        })
        chart.render()
        $('.sort-button').click(function () {
            sortType = sortType === 'positive' ? 'negative' : 'positive'
            sortData(sortType)
            chart.repaint()
        })

        function sortData(sortType) {
            if (sortType === 'positive') {
                data.sort(function (a, b) {
                    return b.value - a.value
                })
            } else {
                data.sort(function (a, b) {
                    return a.value - b.value
                })
            }
        }</script>
{% endblock %}

templates/schedule/schedule_create_form.html
<form action="{% url 'member:dept_create' %}" id="add_dept" method="POST" class="depart">
    <div class="ui dividing header">添加任务</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div class="ui form warning">
            {% for field in form %}
                <div class="field">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
                {% if field.help_text %}
                    <p class="ui warning message" style="padding: 8px 0;">{{ field.help_text }}</p>
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                        <p class="ui negative message" style="padding: 8px 0;">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                class="checkmark icon"></i>
        </button>
    </div>
</form>

templates/schedule/schedule_delete_form.html
<form method="post" action="">
    {% csrf_token %}
    <div class="ui icon header">
        <i class="remove user icon">
        </i> 确认删除"{{ object.job_name }} 编号为{{ object.id }} 的任务吗?
    </div>
    <div class="actions">
        <div class="ui red  cancel inverted button"><i class="remove icon"></i> 否</div>
        <button type="submit" class="ui green ok inverted button"><i class="checkmark icon"></i> 是</button>
    </div>
</form>
{% block style %}
    <style>
        .modal-content form {
            text-align: center;
        }

        .actions {
            margin: 20px;
        }

    </style>
{% endblock %}

templates/schedule/schedule_detail.html
{% extends 'base.html' %}
{% block content %}
    <section>
        <div class="ui segment"><h1 class="ui header aligned center">进度管理</h1>
        <div class="ui secondary pointing menu">

            {% for profess in profess_s %}
            <a class="item
            {% ifequal select_profess profess %}
                active
            {% endifequal %}
                " href="{% url 'schedule:list_profess' profess.id %}">{{ profess.name }}</a>
            {% endfor %}
            <div class="right menu">
                <a href="" class="item">导出全部专业二维码</a>
                <a href="#" class="item add_profess" onclick="return false">添加专业</a>

            </div>
        </div>
             <a href="{% url 'schedule:list' %}">
                <button class="ui right labeled icon button primary basic"><i class="right info icon"></i>进度操作</button>
            </a>
            <div class="ui animated fade right floated button">
                <div class="hidden content"><i class="upload icon"></i></div>
                <div class="visible content">导出全部二维码</div>
            </div>
            <div class="ui buttons right floated">
                <button class="ui labeled icon button right floated my_import"><i class="download icon"></i> 导入</button>
                <div class="or"></div>
                <button class="ui right labeled icon button my_export"><i class="upload icon"></i> 导出</button>
            </div>
            <table class="ui table celled line single fixed" id="table">
                <thead>
                <tr class="center aligned">
                    <th>编号</th>
                    <th>施工地点</th>
                    <th>作业名称</th>
                    <th>专业</th>
                    <th>单位</th>
                    <th>开累完成率</th>
                    <th>设计总量</th>
                    <th>开累完成量</th>
                    <th>剩余总量</th>
                    <th>上周计划完成量</th>
                    <th>上周实际完成量</th>
                    <th>本周计划量</th>
                    <th>完成总周数</th>
                    <th>当前周目</th>
                </tr>
                </thead>
                <tbody>
                {% for item in object_list %}
                <tr class="center aligned">
                    <td>{{ item.id }}</td>
                    <td>{{ item.location }}</td>
                    <td>{{ item.job_name }}</td>
                    <td>{{ item.profess }}</td>
                    <td>{{ item.unit }}</td>
                    <td>{% widthratio  item.done_count  item.design_total  100 %}%</td>
                    <td>{{ item.design_total }}</td>
                    <td>{{ item.done_count }}</td>
                    <td>{{ item.undone_count }}</td>
                    <td>{{ item.last_week_plan }}</td>
                    <td>{{ item.last_week_actual }}</td>
                    <td>{{ item.now_week_plan }}</td>
                    <td>{{ item.now_week_actual}}</td>
                    <td>{{ item.now_week}}</td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="14">
                        <div class="ui pagination menu right floated"><a class="item">1</a>
                            <div class="disabled item">...</div>
                            <a class="item">10</a><a class="item active">11</a><a class="item">12</a></div>
                    </th>
                </tr>
                </tfoot>
            </table>
        </div>
    </section>
{% endblock %}
{% block script %}
    <script>$('.add_depart').click(function () {
        $('.ui.modal.member').modal('show')
    })
    $('.my_edit_member').click(function () {
        $('.ui.modal.edit').modal('show')
    })
    $('.my_qrcode').click(function () {
        $('.ui.modal.qrcode').modal('show')
    })
    $('.my_remove').click(function () {
        $('.ui.modal.remove').modal('show')
    })
    $('.ui.dropdown').dropdown()
    </script>
{% endblock %}

templates/schedule/schedule_update_form.html
<form action="{% url 'member:dept_create' %}" id="add_dept" method="POST" class="depart">
    <div class="ui dividing header">更新任务</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        <div class="ui form warning">
            <div class="four fields">
                {% for field in form %}
                <div class="field">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="ui warning message" style="padding: 8px 0;">{{ field.help_text }}</p>
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                     <p class="ui negative message" style="padding: 8px 0;">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交
            <i class="checkmark icon"></i>
        </button>
    </div>
</form>