Subway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('schedule/',include('schedule.urls')),
    path('device/',include('device.urls')),
    path('material/', include('material.urls')),
    path('technology/', include('technology.urls')),
    path('safety/', include('safety.urls')),
    path('system/', include('system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

material/urls.py
from django.urls import path
from .views import *

app_name = "material"
urlpatterns = [
    path('list', MaterialListView.as_view(), name='list'),
    path('list_profess/<int:profess_id>', MaterialListView.as_view(), name="list_profess"),

    path('add', MaterialAddView.as_view(), name='add'),
    path('update/<int:pk>', MaterialUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', MaterialDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', MaterialDetailView.as_view(), name='detail'),
    path('import', import_material_data, name='import'),
    path('export', export_material_data, name='export'),
    path('export_qr', export_qr, name='export_qr'),

    path('stock/record', MaterialStockRecordView.as_view(), name='stock_record'),
    path('stock/record/<int:pk>', MaterialStockRecordView.as_view(), name='stock_record_with_id'),
    path('stock/in_out/<int:pk>', material_in_out_stock, name='in_out_stock'),

    path('init_profess', ProfessInitView.as_view(), name='init_profess'),
    path('add_profess', ProfessCreateView.as_view(), name='add_profess'),
    path('update_profess/<int:pk>', ProfessUpdateView.as_view(), name='update_profess'),
    path('delete_profess/<int:pk>', ProfessDeleteView.as_view(), name='delete_profess'),
]

member/urls.py
from django.urls import path
from .views import *

app_name = "member"
urlpatterns = [

    path('', index),
    path('auth/login', LoginView.as_view(), name='login'),
    path('auth/logout', logout_view, name='logout'),
    path('global/qrcode/<path:data>', qrcode_view, name='qrcode'),
    path('global/success', success_view, name='success'),
    path('global/depass', depass_view, name='depass'),
    path('member/member_add', MemberAddView.as_view(), name='member_add'),
    path('member/member_list', MemberListView.as_view(), name='member_list'),
    path('member/member_update/<int:pk>', MemberUpdateView.as_view(), name='member_update'),
    path('member/member_delete/<int:pk>', MemberDeleteView.as_view(), name='member_delete'),
    path('member/member_list_detail', MemberListDetailView.as_view(), name='member_list_detail'),
    path('member/member_list_detail/<int:dept_id>', MemberListDetailView.as_view(), name='member_list_detail_with_id'),
    path('member/member_list/<int:dept_id>', MemberListView.as_view(), name='member_list_with_id'),
    path('member/member_import', import_member_data, name='member_import'),
    path('member/member_export', export_member_data, name='member_export'),
    path('member/member_export/<int:dept_id>', export_member_data, name='member_export_with_id'),
    path('member/member_detail/<str:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('member/dept', DeptListView.as_view(), name='dept_list'),
    path('member/dept_create', DeptCreateView.as_view(), name='dept_create'),
    path('member/dept_update/<int:pk>', DeptUpdateView.as_view(), name='dept_update'),
    path('member/dept_delete/<int:pk>', DeptDeleteView.as_view(), name='dept_delete'),
    path('member/dept_assign_account/<int:pk>', AssignAccountView.as_view(), name='dept_assign_account'),
    path('member/dept_assign_account/update/<int:pk>', AssignAccountUpdateView.as_view(), name='update_assign_account'),
    path('member/dept_assign_account/delete/<int:pk>', AssignAccountDeleteView.as_view(), name='delete_assign_account'),
    path('member/dept_assign_account_list', AssignAccountListView.as_view(), name='dept_assign_account_list'),
    path('member/dept_assign_account_list/<int:dept_id>', AssignAccountListView.as_view(), name='accout_list_with_id'),

    path('member/export_qr/<int:dept_id>', export_qr_with_dept, name='export_qr_with_dept')
]

material/models.py
import os
from django.db import models
from django.conf import settings
from core.QR import make_pic

QR_DIR_3 = os.path.join(settings.MEDIA_ROOT, 'material_qr_3')
QR_DIR_2 = os.path.join(settings.MEDIA_ROOT, 'material_qr_2')

QR_3_NAME_TEM = '物资三级二维码_%s.png'
QR_2_NAME_TEM = '物资二级二维码_%s.png'

if not os.path.exists(QR_DIR_3):
    os.makedirs(QR_DIR_3)
if not os.path.exists(QR_DIR_2):
    os.makedirs(QR_DIR_2)


class Material(models.Model):

    # 编号 暂定自增
    id = models.AutoField(primary_key=True, verbose_name='编号')
    name = models.CharField(max_length=155, verbose_name='名称')
    type_id = models.CharField(max_length=20, verbose_name='型号')
    profess = models.ForeignKey(to="Profess", related_name='profess',
                                on_delete=models.SET_NULL, verbose_name='专业', null=True)
    manufacturer = models.CharField(
        max_length=30, verbose_name='生产厂家', default='无')
    num = models.IntegerField(default=0, verbose_name='数量')
    unit = models.CharField(max_length=10, verbose_name='单位')

    def __str__(self):
        return self.name
    
    class Meta:
        """Meta definition for Profess."""

        verbose_name = 'Material'
        verbose_name_plural = 'Materials'
        ordering = ['id']

    @property
    def qrcode(self):
        return '/media/material_qr_3/' + QR_3_NAME_TEM % self.id

    @property
    def profess_name(self):
        return str(self.profess)

    def gen_qrcode_img(self):
        qr = make_pic([str(self.profess), self.name,
                       self.manufacturer], '/material/detail/' + str(self.id))
        qr.save(os.path.join(QR_DIR_3, QR_3_NAME_TEM % self.id), quality=100)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not os.path.exists(os.path.join(QR_DIR_3, QR_3_NAME_TEM % self.id)):
            self.gen_qrcode_img()


class MaterialStock(models.Model):

    operation_choices = (
        (0, 'in'),
        (1, 'out')
    )

    material = models.ForeignKey(
        Material, related_name='record', on_delete=models.CASCADE)
    count = models.IntegerField(default=0, verbose_name='数量')
    operation_date = models.DateTimeField(
        auto_now_add=True, verbose_name='操作日期')
    operation_type = models.IntegerField(
        default=0, choices=operation_choices, verbose_name='操作类型')
    create_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class Profess(models.Model):
    """Model definition for Profess."""
    name = models.CharField(max_length=30)

    class Meta:
        """Meta definition for Profess."""

        verbose_name = 'Profess'
        verbose_name_plural = 'Professs'

    def __str__(self):
        """Unicode representation of Profess."""
        return self.name

    @property
    def qrcode(self):
        return '/media/material_qr_2/' + QR_2_NAME_TEM % self.id

    def gen_qrcode_img(self):
        qr = make_pic(['物资信息', self.name],
                      '/material/list_profess/' + str(self.id))
        qr.save(os.path.join(QR_DIR_2, QR_2_NAME_TEM % self.id), quality=100)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not os.path.exists(os.path.join(QR_DIR_2, QR_2_NAME_TEM % self.id)):
            self.gen_qrcode_img()

material/forms.py
from django import forms
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin
from .models import Material, Profess


class MaterialForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Material
        fields = '__all__'


class ProfessForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):


    """Form definition for Profess."""

    class Meta:
        """Meta definition for Professform."""

        model = Profess
        fields = '__all__'

material/views.py
from django.contrib import messages
from datetime import datetime

import django_excel as excel
from bootstrap_modal_forms.mixins import DeleteAjaxMixin, PassRequestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import IntegrityError, transaction
from django.http import JsonResponse
from django.shortcuts import (HttpResponse, HttpResponseRedirect,
                              get_object_or_404, render)
from django.urls import reverse_lazy
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from core.utils import compress_file

from .forms import MaterialForm, ProfessForm
from .models import *


class MaterialAddView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Material
    form_class = MaterialForm
    template_name = 'material/material_create_form.html'
    success_url = reverse_lazy('material:list')
    success_message = '%(name)s 添加成功'


class MaterialUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Material
    form_class = MaterialForm
    template_name = 'material/material_update_form.html'
    success_url = reverse_lazy('material:list')
    success_message = '%(name)s 更新成功'


class MaterialDetailView(DetailView):
    model = Material
    template_name = "TEMPLATE_NAME"


class MaterialDeleteView(DeleteAjaxMixin, DeleteView):
    model = Material
    form_class = MaterialForm
    template_name = 'material/material_delete_form.html'
    success_url = reverse_lazy('material:list')


class MaterialListView(ListView):
    model = Material
    template_name = 'material/material.html'
    paginate_by = 100

    def __init__(self):
        super().__init__()
        self.profess_all = Profess.objects.all()
        self.profess = self.profess_all[0] if len(self.profess_all) > 0 else 0

    def get(self, request, *args, **kwargs):
        if not self.profess:
            return HttpResponseRedirect(reverse_lazy('material:init_profess'))
        profess_id = kwargs.get('profess_id')
        if profess_id:
            self.profess = get_object_or_404(Profess, pk=profess_id)

        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(MaterialListView, self).get_queryset()
        queryset = queryset.filter(profess=self.profess)
        print(len(queryset))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['profess_s'] = self.profess_all
        context['select_profess'] = self.profess
        return context


class MaterialStockRecordView(ListView):
    model = MaterialStock
    template_name = 'material/material_record.html'

    def get(self, request, *args, **kwargs):
        self.pk = kwargs.get('pk', 0)
        return super(MaterialStockRecordView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super(MaterialStockRecordView, self).get_queryset()
        if self.pk:
            queryset = queryset.filter(material_id=self.pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(MaterialStockRecordView,
                        self).get_context_data(**kwargs)
        context['material_list'] = Material.objects.all()
        if self.pk:
            context['select_material'] = get_object_or_404(
                Material, pk=self.pk)
        else:
            context['select_material'] = '全部'
        return context


class ProfessCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Profess
    form_class = ProfessForm
    template_name = "material/add_update_profess_form.html"
    success_message = '%(name)s 添加成功'
    success_url = reverse_lazy('material:list')


class ProfessInitView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Profess
    form_class = ProfessForm
    template_name = "material/init_profess_form.html"
    success_message = '%(name)s 添加成功'
    success_url = reverse_lazy('material:list')


class ProfessUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Profess
    form_class = ProfessForm
    template_name = "material/add_update_profess_form.html"
    success_message = '%(name)s 更新成功'
    success_url = reverse_lazy('material:list')


class ProfessDeleteView(DeleteView):
    model = Profess
    form_class = ProfessForm
    success_message = '%(name)s 删除成功'
    template_name = "material/delete_profess.html"
    success_url = reverse_lazy('material:list')


def material_in_out_stock(request, **kwargs):
    material = get_object_or_404(Material, pk=kwargs.get('pk'))
    in_or_out = int(request.POST.get('type_id'))  # 0 in 1 out
    count = int(request.POST.get('count'))
    try:
        with transaction.atomic():
            material.num += count if not in_or_out else -count
            material.record.create(
                count=count, operation_type=in_or_out, create_user=request.user)
            material.save()
            return JsonResponse({'msg': 'ok'})
    except Exception as e:
        # raise e
        return JsonResponse({'msg': str(e)})


def import_material_data(request):
    # 导入数据
    mapdict = {
        "名称": "name",
        "生产厂家": "manufacturer",
        "专业id": "profess_id",
        '型号': 'type_id',
        '数量': 'num',
        '单位': 'unit',
    }
    if request.method == "POST":
        try:
            request.FILES['docfile'].save_to_database(
                name_columns_by_row=0,
                model=Material,
                mapdict=mapdict)
            messages.success(request, "导入成功")

        except IntegrityError as e:
            print(e)
            messages.error(
                request, '导入失败：请检查Excel内容是否有以下错误: </br> 1.数据重复</br> 2.专业id不存在')
        except ValueError as e:
            print(e)
            messages.error(
                request, '导入失败：请检查Excel内容是否有以下错误: </br> 1.数据格式错误 例如id类存在汉字或字母')
        except Exception as e:
            messages.error(request, str(e))
        return JsonResponse({'msg': 'd'})
    else:
        pass


def export_material_data(request):
    file_name = '物资表_'
    queryset = Material.objects.all()

    file_name += datetime.now().strftime("%Y-%m-%d")

    column_names = ['id', 'name', 'manufacturer',
                    'profess_id', 'profess_name', 'type_id', 'num', 'unit']
    colnames = ['物资编号', '名称', '生产厂家', '专业id', '专业名称', '型号', '数量', '单位']
    return excel.make_response_from_query_sets(
        queryset,
        column_names,
        'xls',
        file_name=file_name,
        colnames=colnames,
        sheet_name='物资数据',
    )


def export_qr(request, dept_id=None):
    file_name = '物资二维码_'
    qr = Material.objects.all()

    file_name += datetime.now().strftime("%Y-%m-%d") + '.zip'
    s = compress_file(
        [os.path.join(QR_DIR_3, QR_3_NAME_TEM % i.id) for i in qr])
    response = HttpResponse(content_type="application/zip")
    response["Content-Disposition"] = "attachment; filename=" + \
        file_name.encode('utf-8').decode('ISO-8859-1')
    s.seek(0)
    response.write(s.read())
    return response

templates/material/add_update_profess_form.html
<form method="post" enctype="multipart/form-data">
    <div class="ui dividing header">修改/增加专业信息</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
        </div>
        <div class="ui form">
            <div class="four fields">
                {% for field in form %}
                    <div class="field">{{ field }}</div>
                    <div class="{% if field.errors %} invalid{% endif %}">
                        {% for error in field.errors %}
                            <p class="ui negative message" style="padding: 0;">{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                class="checkmark icon"></i>
        </button>
    </div>
</form>

templates/material/material.html
{% extends "base.html" %}
{% block content %}
{% include "_modal.html" %}
<section>
    <div class="ui segment">
        <h1 class="ui header aligned center">物料信息</h1>
        <div class="ui secondary pointing menu">

            {% for profess in profess_s %}
            <a class="item
            {% ifequal select_profess profess %}
                active
            {% endifequal %}
                " href="{% url 'material:list_profess' profess.id %}">{{ profess.name }}</a>
            {% endfor %}
            <div class="right menu">
                <a href="" class="item">导出全部专业二维码</a>
                <a href="#" class="item add_profess" onclick="return false">添加专业</a>

            </div>
        </div>
        <a href="{% url 'material:stock_record' %}">
            <button class="ui right labeled icon button primary"><i class="right info icon"></i> 操作记录</button>
        </a>
        <div class="ui animated fade right floated button">
            <div class="hidden content"><i class="upload icon"></i></div>
            <a class="visible content" href="{% url 'material:export_qr' %}">导出全部二维码</a>
        </div>
        <div class="ui buttons right floated">
            <form action="{% url 'material:import' %}" id="import_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="ui labeled icon button right floated my_import" id="import"><i class="upload icon"></i>
                    导入
                </div>
            </form>
            <div class="or"></div>
            <a class="ui right labeled icon button my_export" href="{% url 'material:export' %}"><i
                    class="download icon"></i>
                导出</a>
        </div>
        <table class="ui table celled line single fixed" id="table">
            <thead>
                <tr class="center aligned">
                    <th>编号</th>
                    <th>物资名称</th>
                    <th>生产厂家</th>
                    <th>专业</th>
                    <th>型号</th>
                    <th>数量</th>
                    <th>单位</th>
                    <th class="four wide">操作</th>
                </tr>
            </thead>
            <tbody>
                {% for material in object_list %}
                <tr class="center aligned">
                    <td>{{ material.id }}</td>
                    <td>{{ material.name }}</td>
                    <td>生产厂家</td>
                    <td>电力变电</td>
                    <td>{{ material.type_id }}</td>
                    <td>{{ material.num }}</td>
                    <td>{{ material.unit }}</td>
                    <td><a class="ui vertical animated button positive basic right floated my_qrcode"
                            href="{{ material.qrcode }}" download>
                            <div class="visible content">二维码</div>
                            <div class="hidden content"><i class="qrcode icon"></i></div>
                        </a><a class="ui vertical animated button primary basic center floated my_edit_member">
                            <div class="visible content">编辑
                            </div>
                            <div class="hidden content update_material"
                                data-id="{% url 'material:update' material.id %}"><i class="edit icon"></i></div>
                        </a><a class="ui vertical animated button primary basic center floated my_edit_member">
                            <div class="visible content">出/入库</div>
                            <div class="hidden content inout_stock"
                                data-id="{% url 'material:in_out_stock' material.id %}"><i class="edit icon"></i></div>
                        </a><a class="ui vertical animated button negative basic center floated my_remove">
                            <div class="visible content ">删除
                            </div>
                            <div class="hidden content delete_material"
                                data-id="{% url 'material:delete' material.id %}"><i class="remove user icon"></i>
                            </div>
                        </a></td>
                </tr>
                {% endfor %}
            </tbody>
            <tfoot>
                <tr>
                    <th colspan="8">
                        <button class="ui labeled icon button positive right floated add_material"><i
                                class="users icon"></i>
                            添加物料
                        </button>
                        <button class="ui labeled icon button blue left floated update_profess"><i
                                class="users icon"></i><span>
                                修改当前专业信息</span>
                        </button>
                        <button class="ui labeled icon button negative left floated delete_profess
                            {% ifequal object_list|length 0 %}
                            {% else %}
                            disabled
                            {% endifequal %}"
                            <i class=" users icon"></i><span> 删除当前专业</span>
                        </button>
                        <a class="ui labeled icon button black basic left floated append" href="{{ select_profess.qrcode }}" download><i
                            class="users icon"></i><span>导出该专业二维码</span></a>
                        {% include '_page.html' %}
                    </th>
                </tr>
            </tfoot>
        </table>
        <div class="ui modal inout_stock">
            <div class="ui dividing header">
                出/入库
            </div>
            <form action="" class="ui form" method="post" id="inout_stock_form">
                {% csrf_token %}
                <div class="image content" style="margin: 20px">
                    <div class="ui form">
                        <div class="ui inline four fields">
                            <div class="field">
                                <input type="number" name="count" placeholder="变动数量">
                            </div>
                            <div class="field">
                                <label for="type_id">操作类型</label>
                                <div class="ui radio checkbox">
                                    <input type="radio" value=0 name='type_id'><label for="">入库</label>
                                </div>
                            </div>
                            <div class="field">
                                <div class="ui radio checkbox">
                                    <input type="radio" value=1 name='type_id'><label for="">出库</label>
                                </div>
                            </div>
                            <div class="field">
                                <label>操作人</label>
                                <p>{{ user }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="actions" style="margin: 10px">
                    <div class="ui black deny button">取消</div>
                    <button type="button" class="ui btn positive right labeled icon button" onclick="inout_stock()">
                        提交<i class="checkmark icon"></i>
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}
{% block script %}
<script>
    $('.add_material').each(function () {
        $(this).modalForm({ formURL: "{% url 'material:add' %}" })
    })
    $(".update_material").each(function () {
        $(this).modalForm({ formURL: $(this).data('id') })
    })
    $(".delete_material").each(function () {
        $(this).modalForm({ formURL: $(this).data('id') })
    })

    $(".hidden.content.inout_stock").click(function () {
        $("#inout_stock_form").attr("action", $(this).data('id'))
        $(".ui.modal.inout_stock").modal('show')
    })

    $('.add_profess').modalForm({ formURL: '{% url 'material:add_profess' %}'})
    $('button.update_profess').modalForm({ formURL: '{% url 'material:update_profess' select_profess.id %}'})
    $('button.delete_profess').modalForm({ formURL: '{% url 'material:delete_profess' select_profess.id %}'})
    {% if profess_isValid %}
    alert("{{ profess_isValid}}")
    {% endif %}

    $('.ui.radio.checkbox').checkbox()
</script>
{% endblock script %}

templates/material/material_create_form.html
<form action="{% url 'member:dept_create' %}" id="add_dept" method="POST" class="depart">
    <div class="ui dividing header">添加物资</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        <div class="ui form warning">
            <div class="four fields">
                {% for field in form %}
                <div class="field">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="ui warning message" style="padding: 8px 0;">{{ field.help_text }}</p>
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                    <p class="ui negative message" style="padding: 8px 0;">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交<i
                class="checkmark icon"></i>
        </button>
    </div>
</form>

templates/material/material_record.html
{% extends "base.html" %}
{% block content %}
    {% include "_modal.html" %}
    <section>
        <div class="ui segment">
            <h1 class="ui header aligned center">操作记录</h1>

            {% for profess in profess_s %}
            <a class="item
            {% ifequal select_profess profess %}
                active
            {% endifequal %}
            " href="{% url 'material:list_profess' profess.id %}">{{ profess.name }}</a>
        {% endfor %}
            <div class="ui floating labeled icon dropdown button">
                <i class="filter icon"></i>
                <label>{{ select_material }}</label>
                <div class="menu">
                    <div class="header"><i class="tags icon"></i>选取物资</div>
                    <div class="divider"></div>
                    <a class="item" href="{% url 'material:stock_record' %}">全部</a>
                    {% for material in material_list %}
                        <a class="item"
                           href="{% url 'material:stock_record_with_id' material.id %}">{{ material.name }} </a>
                    {% endfor %}
                </div>
            </div>
            <a href="{% url 'material:list' %}">
                <button class="ui right labeled icon button primary basic"><i class="right info icon"></i> 物料信息</button>
            </a>
            <table class="ui table celled line single fixed" id="table">
                <thead>
                <tr class="center aligned">
                    <th>编号</th>
                    <th>物资名称</th>
                    <th>型号</th>
                    <th>数量</th>
                    <th>单位</th>
                    <th>操作时间</th>
                    <th>操作类型</th>
                    <th>数量</th>
                    <th>操作人</th>
                </tr>
                </thead>
                <tbody>
                {% for record in object_list %}
                    <tr class="center aligned">
                        <td>{{ record.material.id }}</td>
                        <td>{{ record.material.name }}</td>
                        <td>{{ record.material.type_id }}</td>
                        <td>{{ record.material.num }}</td>
                        <td>{{ record.material.unit }}</td>
                        <td>{{ record.operation_date }}</td>
                        <td>{{ record.operation_type }}</td>
                        <td>{{ record.count }}</td>
                        <td>{{ record.create_user }}</td>
                    </tr>

                {% empty %}
                    <div class="ui icon orange message"><i class="hide icon"></i>
                        <div class="content">
                            <div class="header">目前没有一条数据</div>
                            <p>请试着添加一条数据后再试。</p>
                        </div>
                    </div>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    {% include '_page.html' %}
                </tr>
                </tfoot>
            </table>
        </div>
    </section>


{% endblock content %}
{% block script %}
    <script>
        $('.add_account').each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })
        $(".create_dept").modalForm({formURL: "{% url 'member:dept_create' %}"});
        $(".update_dept").each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })
        $(".delete_dept").each(function () {
            $(this).modalForm({formURL: $(this).data('id')})
        })
    </script>
{% endblock script %}

templates/material/material_update_form.html
<form action="{% url 'member:dept_create' %}" id="add_dept" method="POST" class="depart">
    <div class="ui dividing header">更新物资</div>
    <div class="image content">
        <!--i.close.icon-->
        {% csrf_token %}
        <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
            {% for error in form.non_field_errors %}
            {{ error }}
            {% endfor %}
        </div>
        <div class="ui form warning">
            <div class="four fields">
                {% for field in form %}
                <div class="field">
                    <label>{{ field.label }}</label>
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="ui warning message" style="padding: 8px 0;">{{ field.help_text }}</p>
                {% endif %}
                <div class="{% if field.errors %} invalid{% endif %}">
                    {% for error in field.errors %}
                     <p class="ui negative message" style="padding: 8px 0;">{{ error }}</p>
                    {% endfor %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="actions">
        <div class="ui black deny button">取消</div>
        <button type="submit" class="ui submit-btn btn positive right labeled icon button">提交
            <i class="checkmark icon"></i>
        </button>
    </div>
</form>