Subway/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('schedule/',include('schedule.urls')),
    path('device/',include('device.urls')),
    path('material/', include('material.urls')),
    path('technology/', include('technology.urls')),
    path('safety/', include('safety.urls')),
    path('system/', include('system.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device/urls.py
from django.urls import path
from .views import *

app_name = "device"
urlpatterns = [
    path('list', DeviceListView.as_view(), name='list'),
    path('list_detail', DeviceListDetailView.as_view(), name='list_detail'),
    path('list_profess/<int:profess_id>', DeviceListView.as_view(), name="list_profess"),
    path('list_detail_profess/<int:profess_id>', DeviceListDetailView.as_view(), name='list_detail_profess'),

    path('detail', DeviceDetailView.as_view(), name='detail'),
    path('add', DeviceAddView.as_view(), name='add'),
    path('update/<int:pk>', DeviceUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', DeviceDeleteView.as_view(), name='delete'),

    path('init_profess', ProfessInitView.as_view(), name='init_profess'),
    path('add_profess', ProfessCreateView.as_view(), name='add_profess'),
    path('update_profess/<int:pk>', ProfessUpdateView.as_view(), name='update_profess'),
    path('delete_profess/<int:pk>', ProfessDeleteView.as_view(), name='delete_profess'),

    path('update_test_device/<int:pk>', DeviceTestInfoUpdateView.as_view(), name='update_test_device')
]

member/urls.py
from django.urls import path
from .views import *

app_name = "member"
urlpatterns = [

    path('', index),
    path('auth/login', LoginView.as_view(), name='login'),
    path('auth/logout', logout_view, name='logout'),
    path('global/qrcode/<path:data>', qrcode_view, name='qrcode'),
    path('global/success', success_view, name='success'),
    path('global/depass', depass_view, name='depass'),
    path('member/member_add', MemberAddView.as_view(), name='member_add'),
    path('member/member_list', MemberListView.as_view(), name='member_list'),
    path('member/member_update/<int:pk>', MemberUpdateView.as_view(), name='member_update'),
    path('member/member_delete/<int:pk>', MemberDeleteView.as_view(), name='member_delete'),
    path('member/member_list_detail', MemberListDetailView.as_view(), name='member_list_detail'),
    path('member/member_list_detail/<int:dept_id>', MemberListDetailView.as_view(), name='member_list_detail_with_id'),
    path('member/member_list/<int:dept_id>', MemberListView.as_view(), name='member_list_with_id'),
    path('member/member_import', import_member_data, name='member_import'),
    path('member/member_export', export_member_data, name='member_export'),
    path('member/member_export/<int:dept_id>', export_member_data, name='member_export_with_id'),
    path('member/member_detail/<str:pk>', MemberDetailView.as_view(), name='member_detail'),
    path('member/dept', DeptListView.as_view(), name='dept_list'),
    path('member/dept_create', DeptCreateView.as_view(), name='dept_create'),
    path('member/dept_update/<int:pk>', DeptUpdateView.as_view(), name='dept_update'),
    path('member/dept_delete/<int:pk>', DeptDeleteView.as_view(), name='dept_delete'),
    path('member/dept_assign_account/<int:pk>', AssignAccountView.as_view(), name='dept_assign_account'),
    path('member/dept_assign_account/update/<int:pk>', AssignAccountUpdateView.as_view(), name='update_assign_account'),
    path('member/dept_assign_account/delete/<int:pk>', AssignAccountDeleteView.as_view(), name='delete_assign_account'),
    path('member/dept_assign_account_list', AssignAccountListView.as_view(), name='dept_assign_account_list'),
    path('member/dept_assign_account_list/<int:dept_id>', AssignAccountListView.as_view(), name='accout_list_with_id'),

    path('member/export_qr/<int:dept_id>', export_qr_with_dept, name='export_qr_with_dept')
]

safety/urls.py
from django.urls import path
from .views import *

app_name = "safety"
urlpatterns = [
    path('list', SafetyFileListView.as_view(), name='list'),    # TODO
    path('list/<int:type_id>', SafetyFileListView.as_view(), name='list_with_type'),
    path('add', SafetyFileCreateView.as_view(), name='add'),
    path('update/<int:pk>', SafetyFileUpdatView.as_view(), name='update'),
    path('delete/<int:pk>', SafetyFileDeleteView.as_view(), name='delete'),
    path('detail/<int:pk>', SafetyFileDetailView.as_view(), name='detail'),
    path('export_qr', export_qr, name='export_qr'),

    path('import', import_safety_data, name='import'),
    path('export', export_safety_data, name='export'),

]

system/urls.py
from django.urls import path
from .views import *

app_name = "system"
urlpatterns = [
     path('set_text', SetSystemTextItem, name='set_text'),
     path('set_img', SetSystemImgItem, name='set_img'),


     path('set_qr', SetQrcodeView.as_view(), name='set_qr'),
     path('set_backend', SetBackendView.as_view(), name='set_backend'),
     path('set_mobile', SetMobileView.as_view(), name='set_mobile'),
]

templates/_modal.html
<div class="ui modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-content ">

    </div>
</div>

templates/_page.html
{% if is_paginated %}
    <div class="ui pagination menu right floated">
        {% for foo in paginator.page_range %}
            {% ifequal page_obj.number foo %}
                <a class="item active" href="?page={{ foo }}"> {{ foo }}</a>
            {% else %}
                <a class="item" href="?page={{ foo }}"> {{ foo }}</a>
            {% endifequal %}
        {% endfor %}
    </div>
{% endif %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'style/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static  'style/base.css' %}">
    <script src="{% static 'javascript/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'javascript/semantic.min.js' %}"></script>
    <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    <title>Document</title>
    {% block style %}
    {% endblock style %}
</head>

<body>
<header>
    <div class="ui menu massive">
        <div class="left menu"><a class="active item" id="main">
            <i class="list layout icon"></i>功能</a>
            <div class="item">
                <p>IQ工程管理平台</p>
            </div>
        </div>
        <img src="{% static 'header.png' %}">
        <div class="right menu">
            <div class="item">
                <p>欢迎您,{{ user.username }}</p>
            </div>
            <div class="item"><a class="ui negative button" href="{% url 'member:logout' %}">注销</a></div>
        </div>
    </div>
    <div class="ui sidebar inverted vertical menu">
        <!--a.item 1-->
        <!--a.item 2-->
        <!--a.item 3-->
        <div class="ui inverted accordion">

            {% if user.is_superuser %}


                <div class="item">
                    <div class="title"><i class="dropdown icon"></i> 部门管理</div>
                    <div class="content">
                        <div class="ui secondary vertical pointing menu"><a class="item"
                                                                            href="{% url 'member:dept_list' %}">部分管理</a><a
                                class="item" href="{% url 'member:dept_assign_account_list' %}">账号列表</a></div>
                    </div>
                </div>
            {% endif %}
            <div class="item">
                <div class="title"><i class="dropdown icon"></i> 人员管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu"><a class="item"
                                                                        href="{% url 'member:member_list' %}">员工信息</a><a
                            class="item" href="{% url 'member:member_list_detail' %}">详细信息</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 物资管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu"><a class="item" href="{% url 'material:list' %}">物资信息</a><a
                            class="item" href="{% url 'material:stock_record' %}">进出库记录</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 技术管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu"><a class="item" href="{% url 'technology:list' %}">技术信息</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 设备管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu">
                        <a class="item" href="{% url 'device:list' %}">设备信息</a>
                        <a href="{% url 'device:detail' %}" class="item">设备详情</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 安全管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu"><a class="item"
                                                                        href="{% url 'safety:list' %}">安全信息</a></div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 进度管理</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu">
                        <a class="item" href="{% url 'schedule:list' %}">进度信息</a>
                        <a class="item" href="{% url 'schedule:list_detail' %}">进度详情</a>
                        <a class="item" href="{% url 'schedule:list_chart' %}">进度报表</a></div>
                </div>
            </div>
            <div class="item">
                <div class="title active"><i class="dropdown icon"></i> 系统设置</div>
                <div class="content">
                    <div class="ui secondary vertical pointing menu">
                        <a class="item" href="{% url 'system:set_qr' %}">二维码设置</a>
                        <a class="item" href="{% url 'system:set_backend' %}">后台设置</a>
                        <a class="item" href="{% url 'system:set_mobile' %}">移动端设置</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="message">
    {% if messages %}
        {% for message in messages %}
            <div class="ui {{ message.tags }} global message">
                <i class="close icon"></i>
                <div class="header">{{ message | safe }}</div>
                <p>5秒后关闭</p>
            </div>
            <script>
                let i = 5;
                let a = setInterval(() => {
                    if (i == 1) {
                        $('.message .close').closest('.message').transition('fade')
                        clearInterval(a)
                    } else {
                        i--
                        $('.message.global p').html(i + '秒后关闭')
                    }
                }, 1000)
            </script>
        {% endfor %}
    {% endif %}
</div>
{% block content %}
{% endblock content %}
<footer>
    <div class="main"><img src="{% static 'logo.png' %}"><span>中铁电气化局集团有限公司西安电务工程分公司</span></div>
    <div class="desc">
        <span>©China Railway Electrification Bureau Group Co., Ltd. Xi'an Electrical Engineering Branch</span></div>
</footer>
<script>                
    $('#main').click(function () {
        $('.sidebar').sidebar('toggle')
    })
    $('.ui.accordion').accordion()
    $('.ui.dropdown').dropdown()
    $('.message .close').on('click', function () {
        $(this).closest('.message').transition('fade')
    })

    $('#import').after('<input type="file" id="load_xls" name="docfile" style="display:none" onchange ="uploadFile()" accept="application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">');
    $('#import').click(function () {
        document.getElementById("load_xls").click();
    })

    function inout_stock() {
        var inout_stock_form = $("#inout_stock_form")[0]
        $.ajax({
            url: inout_stock_form.action,
            type: 'POST',
            data: new FormData(inout_stock_form),
            processData: false,
            contentType: false,
            success: function (data) {
                console.log(data)
                location.reload()
            },
            error: function(data){
                location.reload()
            }
        })
    }

    function uploadFile() {
        let import_form = $("#import_form")[0];
        let myform = new FormData(import_form);
        myform.append('file', $('#load_xls')[0].files[0]);
        $.ajax({
            url: import_form.action,
            type: "POST",
            data: myform,
            contentType: false,
            processData: false,
            success: function (data) {
                console.log(data)
                location.reload();

            },
            error: function (data) {
                console.log(data)
            }
        })
    }
</script>
{% block script %}
{% endblock script %}
</body>


</html>

templates/mobile.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>a</title>
    <link rel="stylesheet" href="{% static 'style/semantic.min.css' %}">
    <link rel="stylesheet" href="{% static 'style/mobile.css' %}">
    <script src="{% static 'javascript/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'javascript/semantic.min.js' %}"></script>
    {% block style %}
    {% endblock %}
</head>
<body>
<div class="bg"><img src="../static/mobile.jpg"></div>
<header class="header">
    {% block header %}
    {% endblock %}
    <img src="../static/logo.png">
    <span>IQ信息管理系统</span>
</header>
{% block content %}
{% endblock %}
<footer class="footer">
    <div class="row">中铁电气化局集团有限公司西安电务工程分公司</div>
    <div class="desc">
        <div class="left">©China Railway Electrification Bureau Group Co., Ltd. Xi'an Electrical Engineering Branch
        </div>
        <div class="right"><img src="../static/header.png"></div>
    </div>
</footer>
{% block script %}
{% endblock %}
</body>
</html>